version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: proveedor/provedor-frontend:latest
    container_name: provedor-frontend
    ports:
      - "80:80"
    restart: always
